---
- name: Remove stuff
  community.general.zypper:
    name: "{{ item }}"
    state: absent
  with_items:
    - yast2
    - yast2-*
- name: Lock removed packages
  ansible.builtin.shell: zypper al {{ item }}
  with_items:
    - yast2
    - yast2-*