---
- name: Clone dotconf
  ansible.builtin.git:
    repo: https://github.com/apinter/dotconf.git
    dest: /home/apinter/Project/git/dotconf
    update: true
  become: yes
  become_user: apinter

- name: Symlink configs
  ansible.builtin.file:
    src: /home/apinter/Project/git/dotconf/{{ item }}
    dest: /home/apinter/.config/{{ item }}
    state: link
  become: yes
  become_user: apinter
  loop:
    - fish
    - ranger

- name: Symlink alacritty and kitty related configs
  ansible.builtin.file:
    src: /home/apinter/Project/git/dotconf/{{ item }}
    dest: /home/apinter/.config/{{ item }}
    owner: apinter
    group: users
    state: link
  become: yes
  become_user: apinter
  loop:
    - alacritty
    - kitty

- name: Symlink vim configs
  ansible.builtin.file:
    src: /home/apinter/Project/git/dotconf/vim/{{ item }}
    dest: /home/apinter/.{{ item }}
    state: link
  become: yes
  become_user: apinter
  loop:
    - vimrc
    - vim

- name: Symlink fonts 
  ansible.builtin.file:
    src: /home/apinter/Project/git/dotconf/vim/{{ item }}
    dest: /home/apinter/.local/share/{{ item }}
    state: link
  become: yes
  become_user: apinter
  loop:
    - fonts

- name: Symlink zsh configs
  ansible.builtin.file:
    src: /home/apinter/Project/git/dotconf/zsh/{{ item }}
    dest: /home/apinter/{{ item }}
    state: link
  become: yes
  become_user: apinter
  loop:
    - .zshrc

- name: Symlink git and Ansible configs
  ansible.builtin.file:
    src: /home/apinter/Project/git/dotconf/{{ item }}
    dest: /home/apinter/{{ item }}
    state: link
  become: yes
  become_user: apinter
  loop:
    - .gitconfig
    - .ansible.cfg
