---
- name: Setup flatpak remotes
  ansible.builtin.shell: | 
     sudo -u apinter flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
     flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install rpms
  ansible.builtin.shell: tukit --continue execute zypper in -y "{{ microos_rpm_pkg }}"

- name: Install flatpaks
  ansible.builtin.shell: "flatpak install --user -y {{ flatpak_pkg }}"
  become: yes
  become_user: apinter
  ignore_errors: true

- name: Download logo-ls
  ansible.builtin.get_url:
    url: https://github.com/Yash-Handa/logo-ls/releases/download/v1.3.7/logo-ls_amd64.rpm
    dest: /tmp/logo-ls_amd64.rpm
    mode: '0755'

- name: Install logo-ls
  community.general.zypper:
    name: /tmp/logo-ls_amd64.rpm
    state: present
    disable_gpg_check: true
