---
- name: Set Gnome background and screenshots location
  ansible.builtin.shell: |
    gsettings set org.gnome.desktop.background picture-options none
    gsettings set org.gnome.desktop.background primary-color '#555555'
    gsettings set org.gnome.desktop.background color-shading-type 'solid'
    gsettings set org.gnome.gnome-screenshot auto-save-directory 'file:///home/apinter/Media/Pictures/Screenshots/'
  become: yes
  become_user: apinter
  ignore_errors: yes
  when: toolbox_container == false

- name: Copy mount unit
  ansible.builtin.copy:
    src: home-apinter-Media.mount
    dest: /etc/systemd/system/
    owner: root
    mode: '0644'
  when: toolbox_container == false

- name: Enable mount unit
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: yes
    name: home-apinter-Media.mount
  when: toolbox_container == false

- name: Copy flatpak update unit and timer
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/apinter/.config/systemd/user/
    owner: apinter
    mode: '0744'
  become: yes
  become_user: apinter
  loop:
    - update-user-flatpaks.service
    - update-user-flatpaks.timer
  when: toolbox_container == false

- name: Enable flatpak update timer
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: yes
    name: update-user-flatpaks.timer
    scope: user 
  become: yes
  become_user: apinter
  when: toolbox_container == false

- include_tasks: dotconf.yml
- include_tasks: update_system.yml
- include_tasks: install_packages.yml
- include_tasks: toolbox_prep.yml
  when: toolbox_container == true
