---
- name: Add disks to crypttab
  ansible.builtin.lineinfile:
    path: /etc/crypttab
    line: "{{ item }}"
    state: present
  loop:
    - "cr_home  UUID=ea8b590a-66b9-48eb-8523-18ea94fc29f8  none  x-initrd.attach,discard"
    - "cr_store    UUID=ada7205e-01d2-4faa-af7b-36735e4f07d5  none  x-initrd.attach"

- name: Delete existing /home from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "/home"
    state: absent

- name: Add disks to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
    state: present
  loop:
    - "UUID=92de2953-efba-4a0d-851d-7e2d800da577 /home            btrfs  compress=zstd:1               0  0"
    - "UUID=7c37b228-493d-467e-863c-9ac506a5c087 /home/apinter/Storage    btrfs  compress=zstd:1       0  0"

- name: Mount everything
  ansible.posix.mount:
    path: /home
    src: UUID=92de2953-efba-4a0d-851d-7e2d800da577
    fstype: btrfs
    opts: "compress=zstd:1"
    state: mounted

- name: Set Gnome background and screenshots location
  ansible.builtin.shell: |
    gsettings set org.gnome.desktop.background picture-options none
    gsettings set org.gnome.desktop.background primary-color '#555555'
    gsettings set org.gnome.desktop.background color-shading-type 'solid'
    gsettings set org.gnome.gnome-screenshot auto-save-directory 'file:///home/apinter/Media/Pictures/Screenshots/'
  become: yes
  become_user: apinter

- name: Copy mount unit
  ansible.builtin.copy:
    src: home-apinter-Media.mount
    dest: /etc/systemd/system/
    owner: root
    mode: '0644'

- name: Enable mount unit
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: yes
    name: home-apinter-Media.mount

- name: Copy flatpak update unit and timer
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/apinter/.config/systemd/user/
    owner: apinter
    mode: '0744'
  become: yes
  become_user: apinter
  loop:
    - update-user-flatpaks.service
    - update-user-flatpaks.timer

- name: Enable flatpak update timer
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: yes
    name: update-user-flatpaks.timer

- include_tasks: update_system.yml
- include_tasks: add_repos.yml
- include_tasks: install_packages.yml
- include_tasks: remove_packages.yml
- include_tasks: dotconf.yml
