---
- name: Remove packages
  community.general.zypper:
    name: "{{ item }}"
    state: absent
  loop:
    - yast2
    - yast2-*
    - MozillaFirefox
    - gedit
    - gnome-photos
    - libreoffice
    - vlc
    - yast2

- name: Lock removed packages
  ansible.builtin.shell: zypper al {{ item }}
  loop:
    - yast2
    - yast2-*
    - MozillaFirefox
    - gedit  
    - gnome-photos
    - libreoffice
    - vlc
    - yast2