---
- name: Update openSUSE Tumbleweed hosts
  community.general.zypper:
    name: '*'
    state: dist-upgrade
    update_cache: yes
  when:
    - ansible_distribution == "openSUSE Tumbleweed"
    - ansible_os_family == "openSUSE MicroOS"

- name: Update SLE/openSUSE Leap hosts
  community.general.zypper:
    name: '*'
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "openSUSE Leap"

